[variables]
NPM_CONFIG_LOGLEVEL = "error"
NODE_ENV = "production"

[phases.setup]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "node_modules/.bin/serve dist -s -p $PORT"

[start]
cmd = "serve dist -s -p $PORT"
