#!/usr/bin/env python3
"""
Interactive test script for Neptunize podcast generation.
Prompts user for genre, topic, and storyline, then generates podcast.
"""
import asyncio
import os
import sys
import json
from typing import Dict, Any

# Add the app directory to the Python path
sys.path.append(os.path.join(os.path.dirname(__file__), 'app'))

from app.services.podcast_service import PodcastService
from app.config import get_settings


def display_header():
    """Display the application header."""
    print("=" * 60)
    print("🎙️  NEPTUNIZE PODCAST GENERATOR - INTERACTIVE TEST")
    print("=" * 60)
    print()


def get_genre_selection() -> str:
    """Get podcast genre from user input."""
    genres = {
        "1": "crime",
        "2": "business", 
        "3": "educational",
        "4": "general"
    }
    
    print("📂 SELECT PODCAST GENRE:")
    print("1. Crime/True Crime")
    print("2. Business/Entrepreneurship")
    print("3. Educational/Learning")
    print("4. General/Entertainment")
    print()
    
    while True:
        choice = input("Enter your choice (1-4): ").strip()
        if choice in genres:
            selected_genre = genres[choice]
            print(f"✅ Selected genre: {selected_genre.title()}")
            print()
            return selected_genre
        else:
            print("❌ Invalid choice. Please enter 1, 2, 3, or 4.")


def get_speaker_mode() -> bool:
    """Get speaker mode preference from user."""
    print("🎤 SPEAKER MODE:")
    print("1. Single Speaker (Clean narrative for TTS - Recommended)")
    print("2. Multi-format (With stage directions and formatting)")
    print()
    
    while True:
        choice = input("Enter your choice (1-2): ").strip()
        if choice == "1":
            print("✅ Selected: Single Speaker Mode (TTS Optimized)")
            print()
            return True
        elif choice == "2":
            print("✅ Selected: Multi-format Mode")
            print()
            return False
        else:
            print("❌ Invalid choice. Please enter 1 or 2.")


def get_topic_and_storyline() -> tuple[str, str]:
    """Get topic and storyline from user input."""
    print("📝 PODCAST CONTENT:")
    print()
    
    topic = input("Enter the main topic: ").strip()
    if not topic:
        topic = "General discussion"
    
    print()
    storyline = input("Enter the storyline/description: ").strip()
    if not storyline:
        storyline = f"An interesting discussion about {topic}"
    
    print()
    print(f"✅ Topic: {topic}")
    print(f"✅ Storyline: {storyline}")
    print()
    
    return topic, storyline


def display_enhanced_script(enhanced_script: str):
    """Display the enhanced script with formatting."""
    print("=" * 60)
    print("📜 ENHANCED PODCAST SCRIPT (Generated by OpenAI)")
    print("=" * 60)
    print()
    
    # Split script into paragraphs for better readability
    paragraphs = enhanced_script.split('\n\n')
    for paragraph in paragraphs:
        if paragraph.strip():
            print(paragraph.strip())
            print()
    
    print("=" * 60)
    print()


def display_generation_progress():
    """Display progress indicators."""
    print("🔄 GENERATING PODCAST...")
    print()
    print("1. ✅ Validating input")
    print("2. 🔄 Enhancing script with OpenAI...")


def display_audio_progress():
    """Display audio generation progress."""
    print("2. ✅ Script enhanced successfully")
    print("3. 🔄 Generating audio with ElevenLabs...")


def display_completion(result: Dict[str, Any]):
    """Display completion message with results."""
    print("3. ✅ Audio generated successfully")
    print()
    print("=" * 60)
    print("🎉 PODCAST GENERATION COMPLETE!")
    print("=" * 60)
    print()
    print(f"📁 Audio File: {result.get('audio_file_path', 'N/A')}")
    print(f"⏱️  Duration: {result.get('duration_minutes', 'N/A')} minutes")
    print(f"⚡ Processing Time: {result.get('processing_time_seconds', 'N/A')}s")
    print(f"📊 File Size: {result.get('file_size_bytes', 'N/A')} bytes")
    print(f"🎤 Mode: {'Single Speaker (TTS Optimized)' if result.get('single_speaker_mode', True) else 'Multi-format'}")
    print()
    
    if result.get('audio_file_path'):
        print(f"🎧 Play your podcast: {result['audio_file_path']}")
    print()


def display_error(error: Exception):
    """Display error message."""
    print("❌ ERROR OCCURRED:")
    print(f"   {type(error).__name__}: {str(error)}")
    print()


async def main():
    """Main interactive test function."""
    try:
        # Display header
        display_header()
        
        # Get user inputs
        genre = get_genre_selection()
        single_speaker = get_speaker_mode()
        topic, storyline = get_topic_and_storyline()
        
        # Confirm generation
        print("🚀 Ready to generate podcast!")
        confirm = input("Proceed with generation? (y/N): ").strip().lower()
        if confirm not in ['y', 'yes']:
            print("❌ Generation cancelled.")
            return
        
        print()
        display_generation_progress()
        
        # Initialize settings and service
        settings = get_settings()
        podcast_service = PodcastService()
        
        # Create podcast request
        request_data = {
            "topic": topic,
            "storyline": storyline,
            "podcast_type": genre,
            "target_duration": 5,  # 5 minutes
            "target_audience": "general",
            "focus_area": topic  # Add focus_area for business prompts
        }
        
        # Generate enhanced script first
        if single_speaker:
            enhanced_script = await podcast_service.generate_single_speaker_script(
                topic=topic,
                storyline=storyline,
                podcast_type=genre,
                target_duration=5,
                target_audience="general",
                focus_area=topic
            )
        else:
            enhanced_script = await podcast_service.enhance_script_direct(
                user_input=storyline,
                podcast_type=genre,
                target_duration=5,
                target_audience="general",
                focus_area=topic
            )
        
        # Display the enhanced script
        display_enhanced_script(enhanced_script)
        
        # Ask if user wants to continue with audio generation
        print("👆 This is the script that will be converted to audio.")
        continue_audio = input("Continue with audio generation? (y/N): ").strip().lower()
        if continue_audio not in ['y', 'yes']:
            print("✅ Script generation complete. Audio generation skipped.")
            return
        
        print()
        display_audio_progress()
        
        # Generate full podcast
        result = await podcast_service.generate_podcast(request_data, single_speaker=single_speaker)
        
        # Display results
        display_completion(result)
        
    except KeyboardInterrupt:
        print("\n❌ Generation cancelled by user.")
    except Exception as e:
        print()
        display_error(e)
        print("💡 Make sure your .env file is configured with valid API keys.")


if __name__ == "__main__":
    # Run the interactive test
    asyncio.run(main())
